name: Enforce branch naming convention
on:
  push:
  pull_request:
    branches:
      -main

jobs:
  enforce-branch-naming:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: "([a-z]+)\/(\b[a-z0-9]+(?:['-]?[a-z0-9]+)*\b)" # Regex the branch should match. This example enforces grouping
          allowed_prefixes: 'feature,fix' # All branches should start with the given prefix
          ignore: main # Ignore exactly matching branch names from convention
          min_length: 5 # Min length of the branch name
          max_length: 20 # Max length of the branch name
