name: CICD

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: 🗃  Checkout repo
        uses: actions/checkout@v2

      - name: ⚙️  Configure Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: 📦 Install dependencies
        run: npm ci

      - name: ✏️  Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

  netlify:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: 🗃  Checkout repo
        uses: actions/checkout@v2

      - name: ⚙️  Configure Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: 📦 Install sharp-cli, expo-cli
        run: npm i -g sharp-cli expo-cli

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🏗  Build web
        run: expo build:web

      - name: 🚀 Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=web-build --prod

  eas:
    name: Build Android apk on EAS
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: 🗃  Checkout repo
        uses: actions/checkout@v2

      - name: ⚙️  Configure Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: 📦 Install eas-cli
        run: npm i -g eas-cli

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🚀 Build Android apk on EAS
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --profile=preview --platform=android --clear-cache --non-interactive
