name: Enforce branch naming convention

on:
  push:
  pull_request:
    branches:
      main

jobs:
  enforce_branch_naming:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@v1.0.0
        with:
          regex: "(\b[a-z0-9]+(?:['-]?[a-z0-9]+)*\b)"
          allowed_prefixes: 'feature,fix'
          ignore: main
          min_length: 5
          max_length: 20
